#!/bin/bash
#set -x

PATH="/usr/local/bin:${PATH}"

# Leave empty on a non-test system.
TESTROOT="/opt/stream-archiver-master"

umask g+rw

if ! exec 200>"${TESTROOT}/tmp/stream-uploader.lock"; then
  echo "Could not create lockfile" 1>&2
  exit 1
fi
if ! flock -n 200; then
  exit
fi
trap "rm -f \"${TESTROOT}/tmp/stream-uploader.lock\"" EXIT

cd "${TESTROOT}/var/spool/stream-archiver" || exit

source "${TESTROOT}/opt/stream-archiver/uploader-plugins/youtube"
source "${TESTROOT}/opt/stream-archiver/uploader-plugins/soundcloud"

cd Twitch 2> /dev/null && upload_youtube Twitch
